# Generated by Django 3.2.4 on 2021-06-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Jackets', 'Jackets'), ('Hoodies', 'Hoodies'), ('T-shirts', 'T-shirts'), ('Scarfs', 'Scarfs'), ('Bags', 'Bags')], max_length=10),
        ),
    ]
