# Generated by Django 3.2.4 on 2021-06-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Jackets', 'Jackets'), ('Hoodies', 'Hoodies'), ('Tshirts', 'T-shirts'), ('Scarfs', 'Scarfs'), ('Bags', 'Bags')], max_length=10),
        ),
    ]
