# Generated by Django 3.2.4 on 2021-06-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='item',
        ),
    ]
